### ISSUE TITLE
Creating new task should be done in a new page

### ISSUE THREAD

**Issue by krnekhelesh** [sonrisesoftware/tasks-app#1]
The entire app design looks good, with the exception of the create new tasks dialog. It would be preferable to do this in a pagestack similar to the edit tasks page. The current new task dialog also has text which are not clearly visible due to the color.

http://sonrisesoftware.files.wordpress.com/2013/08/qmlscene-mainview_031.png

**Comment by iBelieve** [comment]
So when should I use sheets? I don't see anything about them in the design guidelines, but the API docs makes it sound like I should use a composer sheet for creating or editing content.

Should I also then use a page stack for the Statistics sheet? (See http://sonrisesoftware.files.wordpress.com/2013/08/qmlscene-mainview_036.png?w=191&h=300)

**Comment by krnekhelesh** [comment]
Yes I would personally put that in a new page as well. To be honest, the sdk designers have not put forth the use case of sheets. And currently sheets look terrible without the awesome suru background gradient colors you have chosen. And I do not see sheets being updated any time soon.

**Comment by iBelieve** [comment]
Okay, I will migrate my sheets to pages.

Where should I put the Create/Cancel buttons for adding a new task? Maybe putting the Create button at the bottom of the page and the Cancel button would be the back button in the page stack?

**Comment by krnekhelesh** [comment]
Put the create button in the toolbar along with the cancel button. Make the toolbar persistent while creating a new task. Something similar as shown here in the add timer preset page (https://lh6.googleusercontent.com/Dfg2ZZFszzy-PK3Y5IMSQZF6j_W_PWS1D8cl1I3IQtqt004pdA_xvTahmW4k2XnM1yB_qYO12w3YP6PUh8WCiPavBzQIiCBpZiyxuLqYUlATtWVpU7WpWhxjlg)

**Comment by iBelieve** [comment]
Cool, thank you for the example. Am I supposed to center them with a divider in the middle, as in the design, or is that just because it is a design sketch?
