### ISSUE TITLE
Sort tasks in task lists

### ISSUE THREAD

**Issue by iBelieve** [sonrisesoftware/tasks-app#12]
It would be nice to be able to sort tasks in task lists in different ways, including:
- Manually (the current default)
- By due date
- By priority
- Alphabetically
- By a formula that calculates the relevance of the tasks by due date, priority, creation date, etc to list the tasks it thinks you should due next.

**Comment by krnekhelesh** [comment]
Nice. I already saw a part of this in the new dynamic layout. Nice work!
