### ISSUE TITLE
Confusing to differentiate between New and Add

### ISSUE THREAD

**Issue by krnekhelesh** [sonrisesoftware/tasks-app#15]
When you select a project and then swipe up to reveal the toolbar, you are presented with several options including "Add" and "New". The add refers to a new task while the new is for the project. This is not really intutive to the user. Please add a more descriptive text.

**Comment by iBelieve** [comment]
I've been pondering this for a while, I really don't like it, but don't know how to fix it.

The problem with adding more descriptive text is that there isn't enough room for wide button labels, the buttons stay the same distance apart, but the labels get really close together.

Perhaps I could move the new button to where a back button would go?

Other than that, I have no idea how to improve it.

**Comment by krnekhelesh** [comment]
yup that's really stupid of the sdk to not take that into consideration. But I might have an idea. Why not remove the word "new or add" and replace them with "Task" and "Project". The + icon already denotes adding/creating something. The text "Task", "Project" will denote what the icon does.

**Comment by krnekhelesh** [comment]
I see that you fixed this in commit https://github.com/iBeliever/tasks-app/commit/79288c75915eaeb6f32b065f9d34cdc0ee17f739, but you missed one spot. In the phone interface, projects tab, when you swipe up, the toolbar shows the + icon with the word "new" instead of "project".

**Comment by iBelieve** [comment]
Ah, thanks for pointing that out. I'll fix that.

So what do you think of it? I still think it doesn't make as much sense as having descriptive text, like "Rename", "Delete", "Add", "New", etc.

**Comment by iBelieve** [comment]
I was able to figure out how to space the toolbar buttons so I can now use "New Project" and "Add Task". Here is how it looks:

![Toolbar icons](http://i.imgur.com/yq8DGwb.png)

Do you think it looks okay? I like it a lot better than having "Task" and "Project".
