### ISSUE TITLE
Swipe action to delete a checklist should describe its action

### ISSUE THREAD

**Issue by krnekhelesh** [sonrisesoftware/tasks-app#16]
While swiping a checklist right to delete it, it should provide a descriptive text like "Delete". I have done this in the clock app. You can take a look at http://bazaar.launchpad.net/~ubuntu-clock-dev/ubuntu-clock-app/trunk/view/head:/common/SwipeDelete.qml.

It adds the text "Delete" and also adds an trash icon.

**Comment by iBelieve** [comment]
I already have a "delete" icon. Do you think I should also have the words "Delete"?

**Comment by krnekhelesh** [comment]
Is that in trunk? Cause I did not see the icon.

**Comment by krnekhelesh** [comment]
A text with an icon would be nice. Something similar to https://lh6.googleusercontent.com/BFTrf2gztajdRrHW3ySvO-y8-Nu5kKpxuGkfMwH-BHpPdYyvppmlsWFYkyMS1gqnlSx59SWwLP7jzY9SHFzlx65T-Lqfv75kA0sBdmIbpYv0nvgg3iprFfvbaw (provided by design)

**Comment by iBelieve** [comment]
I must have forgotten to push :(

Anyway, I'll implement the design. Is it okay to use some of the code you linked for visual consistency, since my project is GPLv3+, and that is GPLv3?

**Comment by krnekhelesh** [comment]
yes you can use the code. We have the same license model.

**Comment by iBelieve** [comment]
Forgot to close this from the pull request
