### ISSUE TITLE
Be able to create a task while in the Upcoming section or tab

### ISSUE THREAD

**Issue by krnekhelesh** [sonrisesoftware/tasks-app#18]
**Phone Interface**
When in the upcoming tab (opened by default on startup), it is nice to see what tasks need attention. It should be able to create a task by swiping up the toolbar. Currently the toolbar shows "+ Project" which practically is not necessary but I leave that up to your decision. A "+ task" toolbar button would be nice. With the current interface it would take 3 steps to create a basic task which is not ideal for a new user.

**Comment by iBelieve** [comment]
This is partially fixed now. The user can now create a task from the upcoming tab, and select a project when creating it. However, I'm still working on the UI for selecting a project when creating a task.

**Comment by iBelieve** [comment]
Finally fixed this with the concept of a permanent "Uncategorized" project. Forgot to close this via the commit.
