### ISSUE TITLE
Buttons should not expand the entire width

### ISSUE THREAD

**Issue by krnekhelesh** [sonrisesoftware/tasks-app#3]
Certain buttons such as "category chooser", "Due Date" have a very large width. If the user maximizes the app on the desktop or tablet, the buttons will be quite large. Their sizes should be constrained properly.

**Comment by iBelieve** [comment]
Do you think that the button should fill the entire width when the app's width is small enough (on the phone) but become constrained to a certain width when the app becomes wider, or should the button always remain the default size?

Also, do you think the text field that appears when editing the task's title (by clicking on it) should also be constrained to a minimum width?

**Comment by krnekhelesh** [comment]
Yes that would be ideal since you wouldn't want a button to span the entire width when in tablet or desktop form. That would be terrible. In the phone, perhaps you can cover the entire width. Nice idea!

**Comment by iBelieve** [comment]
I'm going to close this because now that the tasks page has been completely redesigned, there are no more buttons, everything uses list items.
