### ISSUE TITLE
Better name & description in Ubuntu Touch

### ISSUE THREAD

**Issue by iBelieve** [sonrisesoftware/tasks-app#38]
Should the name be displayed as Ubuntu Tasks or as Tasks?

Also there is a typo in the warning. It says, "lose" instead of "loss".

**Comment by fitojb** [comment]
I think it should be just “Tasks”, that way when translated it wouldn’t require too much UI space…

**Comment by iBelieve** [comment]
I'm thinking the same thing, that it should be just "Tasks", although I'd assume "Ubuntu Tasks" being the name wouldn't get translated, though just "Tasks" would.

Turns out that I already had "Tasks" in the desktop file, so I'll try to verify that's how it appears.
