### ISSUE TITLE
Add support to delete tasks by swiping right

### ISSUE THREAD

**Issue by krnekhelesh** [sonrisesoftware/tasks-app#4]
The clock app has this feature where you can swipe right to delete a timer or an alarm. It would be cool to implement this for tasks. You can even extend this by allowing swiping right to delete and swiping left to edit a task.

**Comment by iBelieve** [comment]
Couldn't that be confused with marking a task as completed? And how often would a user want to delete a task versus just completing it, which also hides it from view?

As for swiping left to edit, you can just click on a task and then click on individual fields to edit them.

**Comment by krnekhelesh** [comment]
Yeah I agree. Just bringing up the idea that you could swipe right/left to do something useful. You can also use it mark a task complete.

**Comment by iBelieve** [comment]
I'd rather use the checkbox to complete a task. The problem with swiping is that it removes the list item, which shouldn't happen when completed tasks are being shown. Also, swiping doesn't make as much sense as checking off a task to complete it.

**Comment by krnekhelesh** [comment]
Thinking about this more, I think you made the right decision.
