### ISSUE TITLE
Nothing is saved

### ISSUE THREAD

**Issue by jdstrand** [sonrisesoftware/tasks-app#45]
Hi,

I'm really excited to start using this app on Ubuntu Touch, but nothing is saved. Steps to reproduce: open the app, create a project, close the app, open the app, the project that was added is missing.

At first I thought it was because application confinement was blocking access to the ubuntu-tasks.db, but I worked around that in apparmor-easyprof-ubuntu 1.0.31 in Ubuntu. I'm using ubuntu-tasks 0.5.1 on Ubuntu Touch (mako/Nexus 4). There are no apparmor denials now so it shouldn't be a permissions problem. I even uninstalled ubuntu-tasks, removed the ubuntu-tasks.db, installed 0.5.1 anew and tried again-- still didn't work (again, no apparmor denials and ubuntu-tasks.db was created successfully).

As an aside-- currently ubuntu-tasks.db is being written out to `~/.local/share/Qt Project/QtQmlViewer/ubuntu-tasks.db` because of LP: #1224126. As mentioned, I have currently worked around this in Ubuntu, but this path will not be allowed for much longer. If you are able, I recommend you change the path to your database to be ~/.local/share/com.ubuntu.developer.mdspencer.ubuntu-tasks/ubuntu-tasks.db to avoid migration problems on upgrades. You may want to comment in the bug how this is affecting your app. See https://wiki.ubuntu.com/SecurityTeam/Specifications/ApplicationConfinement#Application_environment for details.

**Comment by iBelieve** [comment]
Unfortunately, I tried using the path your recommended and it doesn't work. The `~` is not turned into my user directory, but instead the whole path is created as a directory structure under `~/.local/share/Qt Project/QtQmlViewer`.

**Comment by iBelieve** [comment]
So do you know if this is a bug in my app or a problem with the phone/SDK?

**Comment by iBelieve** [comment]
I just figured out that this is due to a bug in the SDK preventing `Component.onDestruction` from being called when the app is stopped.

**Comment by jdstrand** [comment]
On 09/14/2013 09:33 AM, Michael Spencer wrote:

> So do you know if this is a bug in my app or a problem with the phone/SDK?

The SDK is not using the correct path. That is this bug:
https://bugs.launchpad.net/ubuntu/+source/u1db-qt/+bug/1224126

I suggest that you comment there saying that you are trying to use the correct
paths but the SDK is preventing you from doing so.

## 

Email: jamie@strandboge.com
IRC:   jdstrand

**Comment by jdstrand** [comment]
On 09/14/2013 09:56 AM, Michael Spencer wrote:

> I just figured out that this is due to a bug in the SDK preventing
> |Component.onDestruction| from being called when the app is stopped.

Cool, I look forward to the fix! You're app looks very useful. :)

## 

Jamie Strandboge
Targeted Performance Partners
Email: jamie@tpptraining.com

**Comment by iBelieve** [comment]
I've partially fixed this by using a Timer which saves the app's data every 5 seconds. Hopefully that is short enough that the user won't loose anything and long enough to not influence the app's performance.

**Comment by ingmar-** [comment]
This could influence the app's performance and the lifecycle of the flash-memory. I'd like your great app so much, that I would love to see another solution...

**Comment by iBelieve** [comment]
@ingmar- I'd love another solution, but can't think of anything that would work. I tried saving everything whenever something was changed, but that resulting in the app freezing when it would load. Do you have any suggestions?

**Comment by iBelieve** [comment]
This was fixed (properly) a long time ago.
