### ISSUE TITLE
App is slow to start

### ISSUE THREAD

**Issue by jdstrand** [sonrisesoftware/tasks-app#48]
I've been using ubuntu-tasks since it showed up in the Ubuntu App Store, and the more I use it and the more I add to it, the slower it becomes. Startup time is much slower than other apps. I have maybe 15 projects with 5-50 tasks per project.

**Comment by iBelieve** [comment]
Sorry for not getting to this sooner. Today I've started work on a major re-write backend the backend, which will include the following things:
1. A faster backend
2. Better load times
3. Dropped support for Trello integration for two reasons:
   1. Applications should do one thing, and do it well.
   2. Having the Trello integration makes the app more complex and slower

You can track progress on completing this at the [Version 1.0 milestone](https://github.com/iBeliever/tasks-app/issues?milestone=3&state=open).
