### ISSUE TITLE
New design for create and edit task page

### ISSUE THREAD

**Issue by krnekhelesh** [sonrisesoftware/tasks-app#5]
I am not designer, however I feel that the create/edit task page could use a nicer touch. 
- It feels a bit weird because of the order of widgets used. For instance the task name and task description text field are separated by the due date button.
- Secondly, the button used for category and priority needs to be replaced a list view.

Here is a screenshot of a revamped create/edit task page that you can see at http://ubuntuone.com/0S0hGeb784d2lA6lwWWXwV and http://ubuntuone.com/1wxA5mDxBDw911hR3OrwtB.

In case you want to see the source code for that ui, you can find it at http://ubuntuone.com/5BjUwJrs2YWpK9eYWhiIaH

**Comment by iBelieve** [comment]
Nice new design, thank you!

Do you think I should also convert the design of the task view page? I put the title, due date, and priority at the top because it was supposed to be in the header sort of equivalent to the large blank area at the top of lined paper.

I also plan to add a checklist feature. Where should I put the checklist?

The problem with using a ValueSelector for the category is that there isn't a way to have a New Category action. Where do you think I should put that?

**Comment by krnekhelesh** [comment]
Thnx :). So to answer your questions,
1. Yes, you will need to modify the design of the task view page to maintain a consistency. 
2. Regarding the checklist, I think you can add another text field. On pressing "enter" or pressing a button, you can append the checklist to a listmodel. You can have a listview based on the listmodel. Everytime the user adds a new checklist (which adds a new item to the listmodel) the listview will update to show it.
3. For the category chooser, you can use a valueselector and as a last item add "Create new category". On clicking this option, it shows the current new category dialog. You will have to trigger a signal (onValueSelected) or something so that you can check if the user has selected that option. That's one way of how I would do that.

**Comment by iBelieve** [comment]
So using a ValueSelector for priority means I won't be able to show colorized priority. Should I just scrap colors altogether, or put it somewhere else, like maybe changing the page's background gradient to reflect the priority?

For the checklist, I've already figured out how to implement it, I just was wondering where I should put it in relation to the other fields. Should I put it directly below the description field, or below the due date?

Also, for the task view page, should I continue to use the page's header for the category and have a Move action in the toolbar, or should I get rid of the header altogether and just use the ValueSelector for the task view page as well as the task add page?

**Comment by krnekhelesh** [comment]
oh I totally forgot about the colors for the priority. I think you should definitely keep colors since it make it visually easy to identify the high priority tasks. Perhaps you could add a small rectangle to the left the valueselector list which updates based on the choice made by the user. This way they will notice it immediately after making the choice. Changing the background wouldn't work since it will use the same background gradient for all the pages. There is no way to have one particular background only for one page.

After reading your blog post and seeing how you use trello, why not do something similar to what they did. They add the checklist below the description. You will have to ensure that the checklist listview is only visible when the user has added at least one checklist.

For the task view page, it would be better to show the category list similar to the create/edit task page. The header could perhaps be the task title instead. Although then it would be repeated twice.

**Comment by iBelieve** [comment]
I could easily change the background based on the page. I figured out how to do it by adding the `backgroundColor`, `headerColor`, and `footerColor` to certain pages, and then in the `MainView`, check to see if the current page has those properties and then using them instead of the global colors if they exist. So I could either do that or add a small UbuntuShape to the left of the value selector.

**Comment by krnekhelesh** [comment]
I leave this decision up to you. Perhaps you can implement them both and see what looks better. I am just a tiny bit concerned if the background gradient for a high priority task (bright red color) might be a bit too distracting. It may take the attention of the user from the task description, checklist. But again lets see how it is.
