### ISSUE TITLE
Tasks definitely needs a new due date widget

### ISSUE THREAD

**Issue by krnekhelesh** [sonrisesoftware/tasks-app#6]
The current method where a dialog is shown to input the due date will not work since the user wouldnt know which date format to type. As a temporary workaround, you can add a placeholder text to that text field to state which date format to use. But I still think that we need a cool date selector widget.

**Comment by iBelieve** [comment]
I'll add a temporary label saying the the format is "MM/DD/YYYY" or "today" (that's what I've been using, I don't know if others are supported too)

I definitely want to add a date widget. The Calendar app has a somewhat okay time selector that looks like an iOS spinner. I'll probably design something like that. Too bad that the SDK doesn't have spinners!

**Comment by krnekhelesh** [comment]
:+1:
