### ISSUE TITLE
Too many Categories can result in unmanageable tabs

### ISSUE THREAD

**Issue by krnekhelesh** [sonrisesoftware/tasks-app#7]
On trying out the new tasks-view-design branch, I noticed that each category has its own tab. This is a nice idea when the number of categories is small (less than 6 perhaps). Once the number of categories increase, then I am guessing managing the tabs will be quite difficult. Have you thought of what needs to be done in that scenario? Will you have a separate view to filter the tasks by category or something?

**Comment by iBelieve** [comment]
I haven't thought about that yet, but it certainly is a very big problem. I'll try to design a better UI. Maybe have a Tabs component with a Tasks page (a brief overview of upcoming and overdue tasks), and a Categories page with a list of categories that when clicked would push the category on to the page stack.

Another idea might be to have one page with a ValueSelector at the top to change categories. not sure if that would fit in the design guidelines, though.

**Comment by krnekhelesh** [comment]
I guess this bug is now solved with the new branch. But I will let you close it when you merge stuff back to master.

**Comment by iBelieve** [comment]
Yep, I'm going to let GitHub automatically close it when I merge the `adaptive-layout` branch by putting the `Fixed #7` in the pull request.
