### ISSUE TITLE
Adaptive layout for phone, tablet and desktop

### ISSUE THREAD

**Issue by krnekhelesh** [sonrisesoftware/tasks-app#8]
The Ubuntu SDK provides support for dynamic layout. By looking at the app window size, one can dynamically adjust the UI to reflect that. For instance in landscape mode, you could could take advantage of the width. This will earn extra points in the contest.

**Comment by iBelieve** [comment]
To bad you didn't wait a day, I was working on designs for an adaptive layout last night and am planning to work on that today :)

**Comment by krnekhelesh** [comment]
I guess great minds think alike :)
